/**
 * NIRF "data submitted by the institution" PDFs (issue #132): the UG 4-year placement table.
 *
 * Every institution that takes part in the National Institutional Ranking Framework publishes the
 * data it submitted, as a PDF generated by NIRF's data capturing system. The "UG [4 Years
 * Program(s)]: Placement & higher studies for previous 3 years" table has one row per graduating
 * batch with: academic years (intake, lateral entry, graduation), first-year intake and admitted,
 * lateral entries, students graduating in minimum stipulated time, students placed, median salary
 * of placed graduates, and students selected for higher studies.
 *
 * The generator prints pages rotated by 90°, so text runs along the PDF's y axis. Items are first
 * turned into reading coordinates (row downward, col rightward) from each item's own text
 * direction, which handles rotated and upright pages alike.
 */

/** One text item as pdfjs returns it: text plus its transform matrix [a, b, c, d, e, f]. */
export interface PdfItem {
  page: number;
  str: string;
  transform: number[];
}

export interface NirfPlacementRow {
  /** Academic year the batch graduated in, e.g. "2024-25". */
  graduationYear: string;
  /** Students graduating in minimum stipulated time. */
  graduates: number | null;
  placed: number | null;
  /** Median salary of placed graduates, rupees per year. */
  medianSalary: number | null;
  higherStudies: number | null;
}

export interface NirfPlacement {
  instituteName: string | null;
  /** NIRF institute ID, e.g. "IR-E-C-12345". */
  instituteId: string | null;
  rows: NirfPlacementRow[];
}

interface Cell {
  row: number;
  col: number;
  text: string;
}

const PAGE_SPAN = 100_000;
const TABLE_TITLE = /UG\s*\[\s*4\s*Years?\s*Program\(?s?\)?\s*\]\s*:\s*Placement/i;
/** What follows the UG 4-year table: another program's table or another section. */
const NEXT_SECTION = /^\s*((PG|UG|PG-Integrated)[^:]{0,40}:\s*Placement|Ph\.?\s?D|Financial Resources|Sponsored Research|Consultancy|Sustainable|Faculty Details)/i;
const ACADEMIC_YEAR = /^\s*\(?\s*(20\d\d)\s*-\s*(\d\d|20\d\d)\s*\)?\s*$/;

/** Reading coordinates from the item's own text direction (works for rotated pages). */
function toCell(it: PdfItem): Cell {
  const [a, b] = it.transform;
  const len = Math.hypot(a, b) || 1;
  const ux = a / len;
  const uy = b / len;
  const x = it.transform[4];
  const y = it.transform[5];
  // col: position along the text direction; row: position across it, growing downward.
  return { row: it.page * PAGE_SPAN + (uy * x - ux * y), col: ux * x + uy * y, text: it.str.trim() };
}

function toInt(text: string): number | null {
  const t = text.replace(/[,\s]/g, "");
  return /^\d+$/.test(t) ? Number(t) : null;
}

/**
 * Median salary in rupees from what institutions type, e.g. "1000000(Ten Lakhs)", "10,00,000",
 * "550000.00" or "5.5 LPA". Values that cannot be a yearly salary return null.
 */
export function parseSalary(text: string): number | null {
  const m = text.replace(/,/g, "").match(/\d+(\.\d+)?/);
  if (!m) return null;
  let v = Number(m[0]);
  if (v < 200 && /lpa|lakh|lac|lakhs|lacs/i.test(text)) v *= 100_000;
  v = Math.round(v);
  if (v < 10_000 || v > 100_000_000) return null;
  // Institutions write the amount in words too, e.g. "300000(Three Lakhs)". When the lakhs in
  // words disagree with the digits (a typed "3000000(Three lakhs)"), neither can be trusted.
  const lakhsInWords = wordsBefore(text, /\b(lakhs?|lacs?|lacks?)\b/i);
  if (lakhsInWords !== null && lakhsInWords !== Math.floor(v / 100_000)) return null;
  return v;
}

const UNITS: Record<string, number> = {
  one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12,
  thirteen: 13, fourteen: 14, fifteen: 15, sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19,
};
const TENS: Record<string, number> = { twenty: 20, thirty: 30, forty: 40, fourty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90 };

/** The number (1–99) written in words just before `unit`, e.g. "Twenty Five Lakh" → 25; null if none. */
function wordsBefore(text: string, unit: RegExp): number | null {
  const m = text.match(unit);
  if (!m || m.index === undefined) return null;
  const words = text.slice(0, m.index).toLowerCase().replace(/[^a-z\s-]/g, " ").split(/[\s-]+/).filter(Boolean);
  let n = 0;
  let seen = false;
  for (let i = words.length - 1, place = 0; i >= 0 && place < 2; i--, place++) {
    const w = words[i];
    if (w in UNITS && place === 0) n += UNITS[w];
    else if (w in TENS) n += TENS[w];
    else break;
    seen = true;
  }
  return seen ? n : null;
}

/** "2024-25" from "2024-25" or "2024-2025". */
function normYear(text: string): string | null {
  const m = text.match(ACADEMIC_YEAR);
  if (!m) return null;
  return `${m[1]}-${m[2].slice(-2)}`;
}

/**
 * Institute name and NIRF ID, in the layouts colleges publish (#134):
 *  - "Institute Name: X [IR-E-C-12345]" (the DCS PDF), possibly with the address before the ID and
 *    stray spaces inside it ("[IR-E- C-33792]");
 *  - "Institute ID : IR-E-C-11015 Institute Name : X Full Report" (the browser printout).
 */
export function instituteOf(joined: string): { instituteName: string | null; instituteId: string | null } {
  const ID = String.raw`IR\s*-\s*[A-Z]\s*-\s*[A-Z]\s*-\s*\d+`;
  const clean = (id: string) => id.replace(/\s+/g, "");
  const printout = joined.match(new RegExp(`Institute ID\\s*:\\s*(${ID})\\s*Institute Name\\s*:\\s*(.+?)\\s+(?:Full Report|Sanctioned|Academic Year)`));
  if (printout) return { instituteId: clean(printout[1]), instituteName: printout[2].trim() };
  const dcs = joined.match(new RegExp(`Institute Name\\s*:\\s*(.+?)\\s*\\[\\s*(${ID})\\s*\\]`));
  if (dcs) return { instituteId: clean(dcs[2]), instituteName: dcs[1].trim() };
  return { instituteName: null, instituteId: null };
}

/** Parse the UG 4-year placement table. Pure: takes the text items of the whole PDF. */
export function parseNirfPlacement(items: PdfItem[]): NirfPlacement {
  const all = items.filter((i) => i.str.trim()).map(toCell);
  const joined = items.map((i) => i.str).join(" ").replace(/\s+/g, " ");
  const { instituteName, instituteId } = instituteOf(joined);
  const out: NirfPlacement = { instituteName, instituteId, rows: [] };

  const cells = [...all].sort((p, q) => p.row - q.row || p.col - q.col);
  const start = cells.findIndex((c) => TABLE_TITLE.test(c.text));
  if (start < 0) return out;
  const titleRow = cells[start].row;
  const endIdx = cells.findIndex((c, i) => i > start && c.row > titleRow + 1 && (NEXT_SECTION.test(c.text) || TABLE_TITLE.test(c.text)));
  const table = cells.slice(start + 1, endIdx < 0 ? undefined : endIdx);

  // Data rows start with an academic year in the leftmost column.
  const minCol = Math.min(...table.filter((c) => normYear(c.text)).map((c) => c.col));
  const starts = table.filter((c) => normYear(c.text) && Math.abs(c.col - minCol) < 5).map((c) => c.row);
  const rowStarts = starts.filter((r, i) => i === 0 || r - starts[i - 1] > 2);
  if (!rowStarts.length) return out;

  const rowsCells = rowStarts.map((r, i) => {
    const next = rowStarts[i + 1] ?? Infinity;
    return table.filter((c) => c.row >= r - 2 && c.row < next - 2);
  });

  // Column centres from the fullest first line; the graduation year is its last academic year.
  const firstLines = rowsCells.map((rc, i) => rc.filter((c) => Math.abs(c.row - rowStarts[i]) <= 2).sort((p, q) => p.col - q.col));
  const best = firstLines.reduce((p, q) => (q.length > p.length ? q : p), []);
  const centres = best.map((c) => c.col);
  let gradIdx = -1;
  best.forEach((c, i) => { if (normYear(c.text)) gradIdx = i; });
  // Graduates, placed, median salary and higher studies follow the graduation year.
  if (gradIdx < 0 || centres.length < gradIdx + 5) return out;

  for (const rc of rowsCells) {
    const byCol = new Map<number, string[]>();
    for (const c of [...rc].sort((p, q) => p.row - q.row)) {
      let k = 0;
      for (let j = 1; j < centres.length; j++) if (Math.abs(c.col - centres[j]) < Math.abs(c.col - centres[k])) k = j;
      byCol.set(k, [...(byCol.get(k) ?? []), c.text]);
    }
    const text = (k: number) => (byCol.get(k) ?? []).join(" ").trim();
    const graduationYear = normYear(text(gradIdx));
    if (!graduationYear) continue;
    out.rows.push({
      graduationYear,
      graduates: toInt(text(gradIdx + 1)),
      placed: toInt(text(gradIdx + 2)),
      medianSalary: parseSalary(text(gradIdx + 3)),
      higherStudies: toInt(text(gradIdx + 4)),
    });
  }
  return out;
}

/** Problems that make a parsed row unusable (e.g. more students placed than graduated). */
export function rowProblems(r: NirfPlacementRow): string[] {
  const p: string[] = [];
  if (r.graduates === null || r.graduates <= 0) p.push("no graduates");
  if (r.placed !== null && r.graduates !== null && r.placed > r.graduates) p.push("placed > graduates");
  if (r.higherStudies !== null && r.graduates !== null && r.higherStudies > r.graduates) p.push("higher studies > graduates");
  if (r.placed && r.placed > 0 && r.medianSalary === null) p.push("no median salary");
  return p;
}
